# Generated by Django 2.2.4 on 2020-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.IntegerField()),
                ('time_created', models.TimeField(auto_now=True)),
                ('hash_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
