# Generated by Django 2.2.4 on 2020-04-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200408_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LogInActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('log_in_time', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.User')),
            ],
        ),
    ]
