# Generated by Django 2.2.4 on 2020-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200408_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='passwd',
            field=models.CharField(max_length=20),
        ),
    ]
