# Generated by Django 2.2.4 on 2020-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200410_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='passwd',
            field=models.CharField(max_length=500),
        ),
    ]
